# each player has 3 lives
# each turn, a math question is generated by randomly picking 2 numbers between 1 and 20
# if a player answers incorrectly, they lose a life. last person standing wins

# each turn, the current lives of both players are displayed

# classes 
# PLAYER
# @num_lives
# minus_life

# GAME
# @turn
# @turn_player
# @winner
# print_turn
# print_question
# print_winner
# game_loop
# change turn

# QUESTION
# @answer
# @num1
# @num2
# @operation
